# Generated by Django 3.0.4 on 2020-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pricelink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelink',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='products.Store'),
        ),
    ]
